from hazelcast.protocol.client_message import ClientMessage, PARTITION_ID_FIELD_OFFSET, RESPONSE_BACKUP_ACKS_FIELD_OFFSET, UNFRAGMENTED_MESSAGE, TYPE_FIELD_OFFSET
import hazelcast.protocol.bits as Bits
from hazelcast.protocol.codec.builtin import *
from hazelcast.protocol.codec.custom import *
from hazelcast.util import ImmutableLazyDataList

"""
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
"""

# Generated("da5729a49b00ce365164af03d842f1cd")

# hex: 0x000200
REQUEST_MESSAGE_TYPE = 512
# hex: 0x000201
RESPONSE_MESSAGE_TYPE = 513
REQUEST_UUID_FIELD_OFFSET = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
REQUEST_SERIALIZATION_VERSION_FIELD_OFFSET = REQUEST_UUID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
REQUEST_INITIAL_FRAME_SIZE = REQUEST_SERIALIZATION_VERSION_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES
RESPONSE_STATUS_FIELD_OFFSET = RESPONSE_BACKUP_ACKS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES
RESPONSE_MEMBER_UUID_FIELD_OFFSET = RESPONSE_STATUS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES
RESPONSE_SERIALIZATION_VERSION_FIELD_OFFSET = RESPONSE_MEMBER_UUID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
RESPONSE_PARTITION_COUNT_FIELD_OFFSET = RESPONSE_SERIALIZATION_VERSION_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES
RESPONSE_CLUSTER_ID_FIELD_OFFSET = RESPONSE_PARTITION_COUNT_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
RESPONSE_FAILOVER_SUPPORTED_FIELD_OFFSET = RESPONSE_CLUSTER_ID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES

RESPONSE_INITIAL_FRAME_SIZE = RESPONSE_FAILOVER_SUPPORTED_FIELD_OFFSET + Bits.BOOLEAN_SIZE_IN_BYTES


def encode_request(cluster_name, credentials, uuid, client_type, serialization_version, client_hazelcast_version, client_name, labels):
    client_message = ClientMessage.create_for_encode()
    client_message.retryable = True
    client_message.operation_name = "Client.AuthenticationCustom"
    initial_frame = ClientMessage.Frame(bytearray(REQUEST_INITIAL_FRAME_SIZE), UNFRAGMENTED_MESSAGE)
    fixed_size_types_codec.encode_int(initial_frame.content, TYPE_FIELD_OFFSET, REQUEST_MESSAGE_TYPE)
    fixed_size_types_codec.encode_int(initial_frame.content, PARTITION_ID_FIELD_OFFSET, -1)
    fixed_size_types_codec.encode_uuid(initial_frame.content, REQUEST_UUID_FIELD_OFFSET, uuid)
    fixed_size_types_codec.encode_byte(initial_frame.content, REQUEST_SERIALIZATION_VERSION_FIELD_OFFSET, serialization_version)
    client_message.add(initial_frame)
    string_codec.encode(client_message, cluster_name)
    byte_array_codec.encode(client_message, credentials)
    string_codec.encode(client_message, client_type)
    string_codec.encode(client_message, client_hazelcast_version)
    string_codec.encode(client_message, client_name)
    list_multi_frame_codec.encode(client_message, labels, string_codec.encode)
    return client_message


def decode_response(client_message, to_object=None):
    iterator = client_message.frame_iterator()
    response = dict(status=None, address=None, memberUuid=None, serializationVersion=None, serverHazelcastVersion=None, partitionCount=None, clusterId=None, failoverSupported=None)
    initial_frame = iterator.next()
    response["status"] = fixed_size_types_codec.decode_byte(initial_frame.content, RESPONSE_STATUS_FIELD_OFFSET)
    response["memberUuid"] = fixed_size_types_codec.decode_uuid(initial_frame.content, RESPONSE_MEMBER_UUID_FIELD_OFFSET)
    response["serializationVersion"] = fixed_size_types_codec.decode_byte(initial_frame.content, RESPONSE_SERIALIZATION_VERSION_FIELD_OFFSET)
    response["partitionCount"] = fixed_size_types_codec.decode_int(initial_frame.content, RESPONSE_PARTITION_COUNT_FIELD_OFFSET)
    response["clusterId"] = fixed_size_types_codec.decode_uuid(initial_frame.content, RESPONSE_CLUSTER_ID_FIELD_OFFSET)
    response["failoverSupported"] = fixed_size_types_codec.decode_boolean(initial_frame.content, RESPONSE_FAILOVER_SUPPORTED_FIELD_OFFSET)
    response["address"] = codec_util.decode_nullable(iterator, address_codec.decode)
    response["serverHazelcastVersion"] = string_codec.decode(iterator)
    return response


