from hazelcast.protocol.client_message import ClientMessage, PARTITION_ID_FIELD_OFFSET, RESPONSE_BACKUP_ACKS_FIELD_OFFSET, UNFRAGMENTED_MESSAGE, TYPE_FIELD_OFFSET
import hazelcast.protocol.bits as Bits
from hazelcast.protocol.codec.builtin import *
from hazelcast.protocol.codec.custom import *

"""
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
"""

# Generated("6949cc6ad86a0626883c9abaddbf0d56")

# hex: 0x070200
REQUEST_MESSAGE_TYPE = 459264
# hex: 0x070201
RESPONSE_MESSAGE_TYPE = 459265
REQUEST_SESSION_ID_FIELD_OFFSET = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
REQUEST_THREAD_ID_FIELD_OFFSET = REQUEST_SESSION_ID_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES
REQUEST_INVOCATION_UID_FIELD_OFFSET = REQUEST_THREAD_ID_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES
REQUEST_TIMEOUT_MS_FIELD_OFFSET = REQUEST_INVOCATION_UID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
REQUEST_INITIAL_FRAME_SIZE = REQUEST_TIMEOUT_MS_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES
RESPONSE_RESPONSE_FIELD_OFFSET = RESPONSE_BACKUP_ACKS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES

RESPONSE_INITIAL_FRAME_SIZE = RESPONSE_RESPONSE_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES


def encode_request(group_id, name, session_id, thread_id, invocation_uid, timeout_ms):
    client_message = ClientMessage.create_for_encode()
    client_message.retryable = True
    client_message.operation_name = "FencedLock.TryLock"
    initial_frame = ClientMessage.Frame(bytearray(REQUEST_INITIAL_FRAME_SIZE), UNFRAGMENTED_MESSAGE)
    FixedSizeTypesCodec.encode_int(initial_frame.content, TYPE_FIELD_OFFSET, REQUEST_MESSAGE_TYPE)
    FixedSizeTypesCodec.encode_long(initial_frame.content, REQUEST_SESSION_ID_FIELD_OFFSET, session_id)
    FixedSizeTypesCodec.encode_long(initial_frame.content, REQUEST_THREAD_ID_FIELD_OFFSET, thread_id)
    FixedSizeTypesCodec.encode_uuid(initial_frame.content, REQUEST_INVOCATION_UID_FIELD_OFFSET, invocation_uid)
    FixedSizeTypesCodec.encode_long(initial_frame.content, REQUEST_TIMEOUT_MS_FIELD_OFFSET, timeout_ms)
    client_message.add(initial_frame)
    RaftGroupIdCodec.encode(client_message, group_id)
    StringCodec.encode(client_message, name)
    return client_message


def decode_response(client_message):
    iterator = client_message.frame_iterator()
    response = dict(response=None)
    initial_frame = iterator.next()
    response["response"] = FixedSizeTypesCodec.decode_long(initial_frame.content, RESPONSE_RESPONSE_FIELD_OFFSET)
    return response


