from hazelcast.protocol.client_message import ClientMessage, PARTITION_ID_FIELD_OFFSET, RESPONSE_BACKUP_ACKS_FIELD_OFFSET, UNFRAGMENTED_MESSAGE, TYPE_FIELD_OFFSET
import hazelcast.protocol.bits as Bits
from hazelcast.protocol.codec.builtin import *
from hazelcast.protocol.codec.custom import *
from hazelcast.util import ImmutableLazyDataList

"""
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
"""

# Generated("43d431c25d6dc94f334204a24f6c994a")

# hex: 0x070400
REQUEST_MESSAGE_TYPE = 459776
# hex: 0x070401
RESPONSE_MESSAGE_TYPE = 459777
REQUEST_INITIAL_FRAME_SIZE = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
RESPONSE_FENCE_FIELD_OFFSET = RESPONSE_BACKUP_ACKS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES
RESPONSE_LOCK_COUNT_FIELD_OFFSET = RESPONSE_FENCE_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES
RESPONSE_SESSION_ID_FIELD_OFFSET = RESPONSE_LOCK_COUNT_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
RESPONSE_THREAD_ID_FIELD_OFFSET = RESPONSE_SESSION_ID_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES

RESPONSE_INITIAL_FRAME_SIZE = RESPONSE_THREAD_ID_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES


def encode_request(group_id, name):
    client_message = ClientMessage.create_for_encode()
    client_message.retryable = True
    client_message.operation_name = "FencedLock.GetLockOwnership"
    initial_frame = ClientMessage.Frame(bytearray(REQUEST_INITIAL_FRAME_SIZE), UNFRAGMENTED_MESSAGE)
    FixedSizeTypesCodec.encode_int(initial_frame.content, TYPE_FIELD_OFFSET, REQUEST_MESSAGE_TYPE)
    FixedSizeTypesCodec.encode_int(initial_frame.content, PARTITION_ID_FIELD_OFFSET, -1)
    client_message.add(initial_frame)
    RaftGroupIdCodec.encode(client_message, group_id)
    StringCodec.encode(client_message, name)
    return client_message


def decode_response(client_message, to_object=None):
    iterator = client_message.frame_iterator()
    response = dict(fence=None, lockCount=None, sessionId=None, threadId=None)
    initial_frame = iterator.next()
    response["fence"] = FixedSizeTypesCodec.decode_long(initial_frame.content, RESPONSE_FENCE_FIELD_OFFSET)
    response["lockCount"] = FixedSizeTypesCodec.decode_int(initial_frame.content, RESPONSE_LOCK_COUNT_FIELD_OFFSET)
    response["sessionId"] = FixedSizeTypesCodec.decode_long(initial_frame.content, RESPONSE_SESSION_ID_FIELD_OFFSET)
    response["threadId"] = FixedSizeTypesCodec.decode_long(initial_frame.content, RESPONSE_THREAD_ID_FIELD_OFFSET)
    return response


