from hazelcast.protocol.client_message import ClientMessage, PARTITION_ID_FIELD_OFFSET, RESPONSE_BACKUP_ACKS_FIELD_OFFSET, UNFRAGMENTED_MESSAGE, TYPE_FIELD_OFFSET
import hazelcast.protocol.bits as Bits
from hazelcast.protocol.codec.builtin import *
from hazelcast.protocol.codec.custom import *
from hazelcast.util import ImmutableLazyDataList

"""
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
"""

# Generated("3b349eaa8318e91f8459be0bd2cce00f")

# hex: 0x013D00
REQUEST_MESSAGE_TYPE = 81152
# hex: 0x013D01
RESPONSE_MESSAGE_TYPE = 81153
REQUEST_UUID_FIELD_OFFSET = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
REQUEST_INITIAL_FRAME_SIZE = REQUEST_UUID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
RESPONSE_INITIAL_FRAME_SIZE = RESPONSE_BACKUP_ACKS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES


def encode_request(names, uuid):
    client_message = ClientMessage.create_for_encode()
    client_message.retryable = False
    client_message.operation_name = "Map.FetchNearCacheInvalidationMetadata"
    initial_frame = ClientMessage.Frame(bytearray(REQUEST_INITIAL_FRAME_SIZE), UNFRAGMENTED_MESSAGE)
    fixed_size_types_codec.encode_int(initial_frame.content, TYPE_FIELD_OFFSET, REQUEST_MESSAGE_TYPE)
    fixed_size_types_codec.encode_int(initial_frame.content, PARTITION_ID_FIELD_OFFSET, -1)
    fixed_size_types_codec.encode_uuid(initial_frame.content, REQUEST_UUID_FIELD_OFFSET, uuid)
    client_message.add(initial_frame)
    list_multi_frame_codec.encode(client_message, names, string_codec.encode)
    return client_message


def decode_response(client_message, to_object=None):
    iterator = client_message.frame_iterator()
    response = dict(namePartitionSequenceList=None, partitionUuidList=None)
    # empty initial frame
    iterator.next()
    response["namePartitionSequenceList"] = entry_list_codec.decode(iterator, string_codec.decode, entry_list_integer_long_codec.decode)
    response["partitionUuidList"] = entry_list_integer_uuid_codec.decode(iterator)
    return response


