from hazelcast.protocol.client_message import ClientMessage, PARTITION_ID_FIELD_OFFSET, RESPONSE_BACKUP_ACKS_FIELD_OFFSET, UNFRAGMENTED_MESSAGE, TYPE_FIELD_OFFSET
import hazelcast.protocol.bits as Bits
from hazelcast.protocol.codec.builtin import *
from hazelcast.protocol.codec.custom import *

"""
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
"""

# Generated("51a7051b94c20fd74c0bd3b23dfcf376")

# hex: 0x013800
REQUEST_MESSAGE_TYPE = 79872
# hex: 0x013801
RESPONSE_MESSAGE_TYPE = 79873
REQUEST_BATCH_FIELD_OFFSET = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
REQUEST_INITIAL_FRAME_SIZE = REQUEST_BATCH_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
RESPONSE_INITIAL_FRAME_SIZE = RESPONSE_BACKUP_ACKS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES


def encode_request(name, iteration_pointers, batch):
    client_message = ClientMessage.create_for_encode()
    client_message.retryable = True
    client_message.operation_name = "Map.FetchEntries"
    initial_frame = ClientMessage.Frame(bytearray(REQUEST_INITIAL_FRAME_SIZE), UNFRAGMENTED_MESSAGE)
    FixedSizeTypesCodec.encode_int(initial_frame.content, TYPE_FIELD_OFFSET, REQUEST_MESSAGE_TYPE)
    FixedSizeTypesCodec.encode_int(initial_frame.content, REQUEST_BATCH_FIELD_OFFSET, batch)
    client_message.add(initial_frame)
    StringCodec.encode(client_message, name)
    EntryListIntegerIntegerCodec.encode(client_message, iteration_pointers)
    return client_message


def decode_response(client_message):
    iterator = client_message.frame_iterator()
    response = dict(iterationPointers=None, entries=None)
    #empty initial frame
    iterator.next()
    response["iterationPointers"] = EntryListIntegerIntegerCodec.decode(iterator)
    response["entries"] = EntryListCodec.decode(iterator, DataCodec.decode, DataCodec.decode)
    return response


