from hazelcast.protocol.client_message import ClientMessage, PARTITION_ID_FIELD_OFFSET, RESPONSE_BACKUP_ACKS_FIELD_OFFSET, UNFRAGMENTED_MESSAGE, TYPE_FIELD_OFFSET
import hazelcast.protocol.bits as Bits
from hazelcast.protocol.codec.builtin import *
from hazelcast.protocol.codec.custom import *
from hazelcast.util import ImmutableLazyDataList

"""
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
"""

# Generated("82c2523d61a5b82e7aa86ffb071eb86f")

# hex: 0x013F00
REQUEST_MESSAGE_TYPE = 81664
# hex: 0x013F01
RESPONSE_MESSAGE_TYPE = 81665
REQUEST_LISTENER_FLAGS_FIELD_OFFSET = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
REQUEST_LOCAL_ONLY_FIELD_OFFSET = REQUEST_LISTENER_FLAGS_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
REQUEST_INITIAL_FRAME_SIZE = REQUEST_LOCAL_ONLY_FIELD_OFFSET + Bits.BOOLEAN_SIZE_IN_BYTES
RESPONSE_RESPONSE_FIELD_OFFSET = RESPONSE_BACKUP_ACKS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES

RESPONSE_INITIAL_FRAME_SIZE = RESPONSE_RESPONSE_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
EVENT_I_MAP_INVALIDATION_SOURCE_UUID_FIELD_OFFSET = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
EVENT_I_MAP_INVALIDATION_PARTITION_UUID_FIELD_OFFSET = EVENT_I_MAP_INVALIDATION_SOURCE_UUID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
EVENT_I_MAP_INVALIDATION_SEQUENCE_FIELD_OFFSET = EVENT_I_MAP_INVALIDATION_PARTITION_UUID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
EVENT_I_MAP_INVALIDATION_INITIAL_FRAME_SIZE = EVENT_I_MAP_INVALIDATION_SEQUENCE_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES
    #hex: 0x013F02
EVENT_I_MAP_INVALIDATION_MESSAGE_TYPE = 81666
EVENT_I_MAP_BATCH_INVALIDATION_INITIAL_FRAME_SIZE = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
    #hex: 0x013F03
EVENT_I_MAP_BATCH_INVALIDATION_MESSAGE_TYPE = 81667


def encode_request(name, listener_flags, local_only):
    client_message = ClientMessage.create_for_encode()
    client_message.retryable = False
    client_message.operation_name = "Map.AddNearCacheInvalidationListener"
    initial_frame = ClientMessage.Frame(bytearray(REQUEST_INITIAL_FRAME_SIZE), UNFRAGMENTED_MESSAGE)
    fixed_size_types_codec.encode_int(initial_frame.content, TYPE_FIELD_OFFSET, REQUEST_MESSAGE_TYPE)
    fixed_size_types_codec.encode_int(initial_frame.content, PARTITION_ID_FIELD_OFFSET, -1)
    fixed_size_types_codec.encode_int(initial_frame.content, REQUEST_LISTENER_FLAGS_FIELD_OFFSET, listener_flags)
    fixed_size_types_codec.encode_boolean(initial_frame.content, REQUEST_LOCAL_ONLY_FIELD_OFFSET, local_only)
    client_message.add(initial_frame)
    string_codec.encode(client_message, name)
    return client_message


def decode_response(client_message, to_object=None):
    iterator = client_message.frame_iterator()
    response = dict(response=None)
    initial_frame = iterator.next()
    response["response"] = fixed_size_types_codec.decode_uuid(initial_frame.content, RESPONSE_RESPONSE_FIELD_OFFSET)
    return response


def handle(client_message, handle_i_map_invalidation_event=None, handle_i_map_batch_invalidation_event=None, to_object=None):
    message_type = client_message.get_message_type()
    iterator = client_message.frame_iterator()
    if message_type == EVENT_I_MAP_INVALIDATION_MESSAGE_TYPE and handle_i_map_invalidation_event is not None:
        initial_frame = iterator.next()
        source_uuid = fixed_size_types_codec.decode_uuid(initial_frame.content, EVENT_I_MAP_INVALIDATION_SOURCE_UUID_FIELD_OFFSET)
        partition_uuid = fixed_size_types_codec.decode_uuid(initial_frame.content, EVENT_I_MAP_INVALIDATION_PARTITION_UUID_FIELD_OFFSET)
        sequence = fixed_size_types_codec.decode_long(initial_frame.content, EVENT_I_MAP_INVALIDATION_SEQUENCE_FIELD_OFFSET)
        key = to_object(codec_util.decode_nullable(iterator, data_codec.decode))
        handle_i_map_invalidation_event(key=key, source_uuid=source_uuid, partition_uuid=partition_uuid, sequence=sequence)
    if message_type == EVENT_I_MAP_BATCH_INVALIDATION_MESSAGE_TYPE and handle_i_map_batch_invalidation_event is not None:
        # empty initial frame
        iterator.next()
        keys = ImmutableLazyDataList(list_multi_frame_codec.decode(iterator, data_codec.decode), to_object)
        source_uuids = list_uuid_codec.decode(iterator)
        partition_uuids = list_uuid_codec.decode(iterator)
        sequences = list_long_codec.decode(iterator)
        handle_i_map_batch_invalidation_event(keys=keys, source_uuids=source_uuids, partition_uuids=partition_uuids, sequences=sequences)
