from hazelcast.protocol.client_message import ClientMessage, PARTITION_ID_FIELD_OFFSET, RESPONSE_BACKUP_ACKS_FIELD_OFFSET, UNFRAGMENTED_MESSAGE, TYPE_FIELD_OFFSET
import hazelcast.protocol.bits as Bits
from hazelcast.protocol.codec.builtin import *
from hazelcast.protocol.codec.custom import *
from hazelcast.util import ImmutableLazyDataList

"""
 * This file is auto-generated by the Hazelcast Client Protocol Code Generator.
 * To change this file, edit the templates or the protocol
 * definitions on the https://github.com/hazelcast/hazelcast-client-protocol
 * and regenerate it.
"""

# Generated("7a611a8767ed07c602c3ec35ffdbb789")

# hex: 0x1D0100
REQUEST_MESSAGE_TYPE = 1900800
# hex: 0x1D0101
RESPONSE_MESSAGE_TYPE = 1900801
REQUEST_TARGET_REPLICA_UUID_FIELD_OFFSET = PARTITION_ID_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES
REQUEST_INITIAL_FRAME_SIZE = REQUEST_TARGET_REPLICA_UUID_FIELD_OFFSET + Bits.UUID_SIZE_IN_BYTES
RESPONSE_VALUE_FIELD_OFFSET = RESPONSE_BACKUP_ACKS_FIELD_OFFSET + Bits.BYTE_SIZE_IN_BYTES
RESPONSE_REPLICA_COUNT_FIELD_OFFSET = RESPONSE_VALUE_FIELD_OFFSET + Bits.LONG_SIZE_IN_BYTES

RESPONSE_INITIAL_FRAME_SIZE = RESPONSE_REPLICA_COUNT_FIELD_OFFSET + Bits.INT_SIZE_IN_BYTES


def encode_request(name, replica_timestamps, target_replica_uuid):
    client_message = ClientMessage.create_for_encode()
    client_message.retryable = True
    client_message.operation_name = "PNCounter.Get"
    initial_frame = ClientMessage.Frame(bytearray(REQUEST_INITIAL_FRAME_SIZE), UNFRAGMENTED_MESSAGE)
    FixedSizeTypesCodec.encode_int(initial_frame.content, TYPE_FIELD_OFFSET, REQUEST_MESSAGE_TYPE)
    FixedSizeTypesCodec.encode_int(initial_frame.content, PARTITION_ID_FIELD_OFFSET, -1)
    FixedSizeTypesCodec.encode_uuid(initial_frame.content, REQUEST_TARGET_REPLICA_UUID_FIELD_OFFSET, target_replica_uuid)
    client_message.add(initial_frame)
    StringCodec.encode(client_message, name)
    EntryListUUIDLongCodec.encode(client_message, replica_timestamps)
    return client_message


def decode_response(client_message, to_object=None):
    iterator = client_message.frame_iterator()
    response = dict(value=None, replicaTimestamps=None, replicaCount=None)
    initial_frame = iterator.next()
    response["value"] = FixedSizeTypesCodec.decode_long(initial_frame.content, RESPONSE_VALUE_FIELD_OFFSET)
    response["replicaCount"] = FixedSizeTypesCodec.decode_int(initial_frame.content, RESPONSE_REPLICA_COUNT_FIELD_OFFSET)
    response["replicaTimestamps"] = EntryListUUIDLongCodec.decode(iterator)
    return response


