[tool.black]
line-length = 100
exclude = '''
(
    /(
        \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist

      | benchmarks
      | hazelcast/protocol/codec
      | hazelcast/serialization
      | tests
    )/
  | /hazelcast/(?!(__init__))\w+\.py
)
'''
