name: membership-test

on:
  pull_request:
  workflow_dispatch:
      
jobs:
  check_for_membership:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Check membership of given user  
    outputs:
      check-result: ${{ steps.composite.outputs.check-result }}
    steps: 
      - name: Action for membership check
        id: composite
        uses: hazelcast/hazelcast-tpm/membership@main
        with:
          member-name: ${{ github.actor }}
          token: ${{ github.token }}

  run-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: check_for_membership
    steps:
      - run: echo "gh api repos/${GITHUB_REPOSITORY}/collaborators/JackPGreen"
      - run: gh api "repos/${GITHUB_REPOSITORY}/collaborators/JackPGreen"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: echo hello-world
