name: Update Let's Encrypt certificate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # monthly
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update_lets_encrypt_certificate.yml'
jobs:
  update_certificate:
    runs-on: ubuntu-latest
    name: Update Let's Encrypt certificate
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout to certificates
        uses: actions/checkout@v3
        with:
          repository: hazelcast/private-test-artifacts
          path: certs
          ref: data
      - name: Extract the certificate
        working-directory: certs
        run: |
          unzip certs.jar
      - name: Checkout to client
        uses: actions/checkout@v3
        with:
          repository: hazelcast/hazelcast-python-client
          path: client
      - name: Copy updated certificate
        run: |
          cp $GITHUB_WORKSPACE/certs/com/hazelcast/nio/ssl/letsencrypt.jks $GITHUB_WORKSPACE/client/tests/integration/backward_compatible/ssl_tests/keystore.jks
      - name: Commit changes
        working-directory: client
        run: |
          gh api user | jq -r '.login'
          git config --global user.name 'devOpsHazelcast'
          git config --global user.email 'devops@hazelcast.com'
          git add tests/integration/backward_compatible/ssl_tests/keystore.jks
          git commit -m "Update Let's Encrypt Certificate"
          git push
